name: "Setup & Dependencies"
description: "Set up Python and install dependencies"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found; installing minimal deps"
          pip install requests openai langchain-ibm
        fi
