name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  pr-review:
    runs-on: ubuntu-latest

    steps:
      # stays as a separate step (can't be grouped because it's an action)
      - name: Checkout code
        uses: actions/checkout@v3

      # one grouped step for Python + dependencies (no subfolder, no path issues)
      - name: Grouped Setup (Python + Dependencies)
        shell: bash
        run: |
          echo "::group::Python"
          python3 --version || true
          python3 -m pip install --upgrade pip
          echo "::endgroup::"

          echo "::group::Install dependencies"
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests openai
          fi
          echo "::endgroup::"

      - name: Run AI PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
          WATSONX_URL: "https://us-south.ml.cloud.ibm.com"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "::group::Run PR Review"
          python PR_Review_OpenAI.py ${{ github.event.pull_request.number }}
          echo "::endgroup::"
