name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  pr-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
          WATSONX_URL: "https://us-south.ml.cloud.ibm.com"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python PR_Review_OpenAI.py ${{ github.event.pull_request.number }}
