name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Dependencies
        uses: ./.github/actions/setup
        with:
          python-version: "3.11"

      - name: Run AI PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
          WATSONX_URL: "https://us-south.ml.cloud.ibm.com"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python PR_Review_OpenAI.py ${{ github.event.pull_request.number }}
